### ISSUE TITLE
Coloured dots not showing up in post edit screen

### ISSUE THREAD

**Issue by attentiondesign** [senlin/so-clean-up-wp-seo#47]
With the latest update of Yoast SEO (9.2), the coloured rating dots have disappeared from the sidebar metabox in the page and post edit screen. The text description (e.g. "SEO: okay") is there but no coloured dots for rating or readability. The one in the admin toolbar is showing (I've got that set to not be hidden). I did update settings for Bloat after the update. This is happening on multiple sites I manage. I can't find any setting for Bloat that should be making the dots disappear.

They are displaying as expected in the column in the lists of pages and posts.

Thanks! Very useful plugin!

**Comment by senlin** [comment]
Thank you for reporting this issue.

To be honest with the rate they pump out updates, we haven't had the chance yet to have a look at it.

When we have a moment we will have a look to see what adjustments are needed to make the dots disappear. 

In the meantime it would be very helpful if you could add a screenshot of the problem.

**Comment by senlin** [comment]
Okay, we had a look, but cannot reproduce the issue.

As far as we can see there are no dots present anymore and they have been replaced by a bar that changes color depending on the length. 

In the version that we have just released we have added an option that hides these colored bars and we have done some more adjustments.

Please try out the new version and report back when you have done. If the issue that you reported still exists, then please show screenshots to illustrate what you mean.

Thanks

**Comment by senlin** [comment]
@attentiondesign 
As I haven't heard back, I'm closing this issue. If you want to re-open it at a later stage, then by all means.

**Comment by attentiondesign** [comment]
Ummm, it was the weekend, I wasn't exactly working on this stuff. That's way too quick to close the issue. 
I will try the new version, and post a screen shot if the problem is still there.

**Comment by attentiondesign** [comment]
Updated plugin, re-saved settings with the coloured bar option not hidden, still the same missing dots in the publish metabox. 2 screenshots attached - the SEO metabox with happy face dots showing as expected; and the publish metabox with missing dots, only text.

![screenshot_2018-10-29 edit page west coast wilderness lodge wordpress2](https://user-images.githubusercontent.com/44538447/47660689-cabe3900-db54-11e8-9df2-236d76815a3a.png)
![screenshot_2018-10-29 edit page west coast wilderness lodge wordpress](https://user-images.githubusercontent.com/44538447/47660690-cabe3900-db54-11e8-843b-46dd5f369a84.png)

**Comment by senlin** [comment]
Well, I figured because you also posted the issue in the weekend :)

Looking at your screenshot, it is not entirely clear where the colored dots need to show? Could you perhaps also do a screenshot with the Hide SEO Bloat plugin deactivated, so we can see what is missing according to you?

**Comment by senlin** [comment]
Okay, I will save you the trouble. 

The Yoast SEO plugin no longer contains colored balls it seems, which can be checked by deactivating Hide SEO Bloat.

Anyways, thanks for opening the issue, so I could implement the changes yesterday.
